### ISSUE TITLE
Users are being unsubscribed mysteriously 

### ISSUE THREAD

**Issue by WinstonN** [ebizmarts/magemonkey#141]
Hello

We are using version 1.2.3

Suddenly we are getting reports from our users that they received unsubscribe notifications. Our users are getting pretty frustrated by this. 
We have no magemonkey crons enabled. After reading this post: http://ebizmarts.com/forums/topics/view/22585

I think it could be due to an observer. I saw this method registerCheckoutSubscribe which seems to be misbehaving. 

Essentially in my admin I have this setting: Subscribe On Checkout set to  Disabled. Which means, that my users are already subscribed, and on checkout, don't do anything to them. 

```
$subscribe = Mage::app()->getRequest()->getPost('magemonkey_subscribe');
if (!is_null($subscribe) || Mage::getStoreConfig(Ebizmarts_MageMonkey_Model_Config::GENERAL_CHECKOUT_SUBSCRIBE) >= 3) {
```

In our case that will be null, which then does:
```
Mage::getSingleton('core/session')->setMonkeyCheckout(true);
```

I am unsure what that line of code does, 

In the mean time I will try and disable those events on checkout, because honestly, we are just using the extension to subscribe users to a list, and we don't want to extension to mange our subscriptions at the checkout. 

Can someone give me some advice about this though?

Thank you for everything that you guys do for the Magento community

Winst

**Comment by WinstonN** [comment]
In the interim I have disabled a few events that the module listens to that we don't need. Will keep you posted with the outcome of this

**Comment by Santiagoebizmarts** [comment]
@WinstonN Hello,
Thanks for contacting us. Please note that there is a "**!**" so without the POST "**magemonkey_subscriber**" that if should return false and do nothing. Specially if you have a custom checkout because our checkout subscription only works with Magento's One Page checkout unless you force it.

Are you sure It is subscribing on the checkout? 

Regards,
Santiago.

**Comment by WinstonN** [comment]
It's not subscribing, but rather UN-subscribing our customers. I am not
sure that it is unsubscribing during the checkout, but it's not a cron.
I have in the mean time turned off all the events except
newsletter_subscribe and newsletter_unsubscribe (<-- incorrect naming)

Will keep an eye on it and see if it happens again

On Thu, Jul 28, 2016 at 3:44 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
The Update Customer event should be enabled as well to get the information updated. This is the one that might be causing problems though. It is supposed to avoid running on checkout but since your checkout is custom it might be running anyways.
Please check the [UpdateCustomer]( https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L292-L358) function, specially [this line](https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L301) and make sure it has the modulename on your checkout as well.

Regards.
